module.exports.categories = {
  "To Read": [
    '/Books & Literature',
    '/Books & Literature/Children\'s Literature',
    '/Books & Literature/E-Books',
    '/Books & Literature/Fan Fiction',
    '/Books & Literature/Literary Classics',
    '/Books & Literature/Poetry',
    '/Books & Literature/Writers Resources',
  ],
  "To Watch": [
    '/Arts & Entertainment/Events & Listings/Movie Listings & Theater Showtimes',
    '/Arts & Entertainment/TV & Video/TV Shows & Programs',
    '/Arts & Entertainment/Entertainment Industry/Film & TV Industry',
    '/Arts & Entertainment/Events & Listings/Film Festivals',
    '/Arts & Entertainment/Comics & Animation/Cartoons',
    '/Arts & Entertainment/Comics & Animation/Anime & Manga',
    '/Arts & Entertainment/Movies',
    '/Arts & Entertainment/TV & Video',
    '/Arts & Entertainment/TV & Video/Online Video',
    '/Arts & Entertainment/TV & Video/TV Commercials',
  ],
  "To Eat": [
    '/Business & Industrial/Hospitality Industry/Food Service',
    '/Food & Drink',
    '/Food & Drink/Beverages',
    '/Food & Drink/Beverages/Alcoholic Beverages',
    '/Food & Drink/Beverages/Coffee & Tea',
    '/Food & Drink/Beverages/Juice',
    '/Food & Drink/Beverages/Soft Drinks',
    '/Food & Drink/Cooking & Recipes',
    '/Food & Drink/Cooking & Recipes/BBQ & Grilling',
    '/Food & Drink/Cooking & Recipes/Desserts',
    '/Food & Drink/Cooking & Recipes/Soups & Stews',
    '/Food & Drink/Food',
    '/Food & Drink/Food & Grocery Retailers',
    '/Food & Drink/Food/Baked Goods',
    '/Food & Drink/Food/Breakfast Foods',
    '/Food & Drink/Food/Candy & Sweets',
    '/Food & Drink/Food/Grains & Pasta',
    '/Food & Drink/Food/Meat & Seafood',
    '/Food & Drink/Food/Snack Foods',
    '/Food & Drink/Restaurants',
    '/Food & Drink/Restaurants/Fast Food',
    '/Food & Drink/Restaurants/Pizzerias',
    '/Food & Drink/Restaurants/Restaurant Reviews & Reservations'
  ],
  "To Buy": [
    '/Pets & Animals/Animal Products & Services/Pet Food & Supplies',
    '/Pets & Animals/Animal Products & Services/Veterinarians',
    '/Arts & Entertainment/Music & Audio/CD & Audio Shopping',
    '/Autos & Vehicles/Vehicle Shopping',
    '/Autos & Vehicles/Vehicle Shopping/Used Vehicles',
    '/Shopping',
    '/Shopping/Antiques & Collectibles',
    '/Shopping/Apparel',
    '/Shopping/Apparel/Athletic Apparel',
    '/Shopping/Apparel/Casual Apparel',
    '/Shopping/Apparel/Children\'s Clothing',
    '/Shopping/Apparel/Clothing Accessories',
    '/Shopping/Apparel/Costumes',
    '/Shopping/Apparel/Eyewear',
    '/Shopping/Apparel/Footwear',
    '/Shopping/Apparel/Formal Wear',
    '/Shopping/Apparel/Headwear',
    '/Shopping/Apparel/Men\'s Clothing',
    '/Shopping/Apparel/Swimwear',
    '/Shopping/Apparel/Undergarments',
    '/Shopping/Apparel/Women\'s Clothing',
    '/Shopping/Auctions',
    '/Shopping/Classifieds',
    '/Shopping/Consumer Resources',
    '/Shopping/Consumer Resources/Consumer Advocacy & Protection',
    '/Shopping/Consumer Resources/Coupons & Discount Offers',
    '/Shopping/Consumer Resources/Product Reviews & Price Comparisons',
    '/Shopping/Entertainment Media',
    '/Shopping/Entertainment Media/Entertainment Media Rentals',
    '/Shopping/Gifts & Special Event Items',
    '/Shopping/Gifts & Special Event Items/Cards & Greetings',
    '/Shopping/Gifts & Special Event Items/Flowers',
    '/Shopping/Gifts & Special Event Items/Gifts',
    '/Shopping/Luxury Goods',
    '/Shopping/Mass Merchants & Department Stores',
    '/Shopping/Photo & Video Services',
    '/Shopping/Tobacco Products',
    '/Shopping/Toys',
    '/Shopping/Toys/Building Toys',
    '/Shopping/Toys/Die-cast & Toy Vehicles',
    '/Shopping/Toys/Dolls & Accessories',
    '/Shopping/Toys/Ride-On Toys & Wagons',
    '/Shopping/Toys/Stuffed Toys',
    '/Computers & Electronics/Software/Business & Productivity Software',
  ]
}

  